# Generated by Django 3.2.16 on 2023-01-24 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 20, 1, 29, 194809, tzinfo=utc)),
        ),
    ]
