# Generated by Django 3.2.16 on 2023-01-24 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_auto_20230124_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 20, 13, 11, 201056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
